### ISSUE TITLE
elementRef.current is null in showMenu

### ISSUE THREAD

**Issue by jeremycod** [breeffy/react-native-popup-menu#3]
Hi,

I have 2 almost identical components that are using react-native-popup-menu v0.8.
Menu in the first component AddressCard is working, though I had several time problem that it stopped working if I change something completely not related to popup menu, and once I had to completely wipe data from emulator in order to make it work again.
Second component ReminderCard which looks almost identical and is used in the similar context never had menu working and reason is that in showMenu elementRef.current is null.

Is there any way to make this more reliable?

[Archive.zip](https://github.com/breeffy/react-native-popup-menu/files/4998732/Archive.zip)

**Comment by likern** [comment]
This part is not related to popup menu.
For setting correct reference to element - it is React Native responsible for. It should always work and should be reliable.

Have you used https://en.reactjs.org/docs/forwarding-refs.html to pass reference down to native component?
Only native components can have / set reference.

Also you can change reference pass to function callback and check what ref argument is passed.
```ts
  const setElementRef: (instance: ElementToStick | null) => void = (ref) => (elementRef = ref);
```

**Comment by jeremycod** [comment]
Hi,

I've tried forward refs and everything else that came to my mind and couldn't make it work. I've tried to reproduce the problem in simpler example, so I've copied the whole component into the other app that you've seen earlier https://github.com/jeremycod/mobiletest and which you've fixed earlier when I've reported previous bug.

After adding new component ReminderCard, menu was working fine as long as there was one ReminderCard on the screen. As soon as I've added another instance of the same component, only the last component was working. Menu on all other components stopped working. It also affected component AddressCard which was working when there were multiple instances.
 
So, this is situation I have now in this sample app:
1 to many AddressCard components on the screen work fine
multiple AddressCard(s) + ReminderCard works fine
multiple AddressCard(s) + 2 ReminderCards - nothing is working except the last ReminderCard

I guess there is some conflicts between references, though it's weird that in real app it doesn't work even when there is only 1 instance of the component on the screen.

Do you have any idea?

**Comment by likern** [comment]
@jeremycod It's difficult to say something definite without reproduction repository.

I haven't had that type of issue, but don't use popup in production.

I think that might be related to new version of React Native. What version do you use? They easily can break even core functionality.

Also it might be related to reference not being set. Probably the previous issue was similar to that problem. But I fixed that (in master, not released on npm).

Do you use master branch with previous fixes?

**Comment by jeremycod** [comment]
I was using master with previous fixes. My main project is similar, just more complex and depends on backend.

Can you check another branch that I've just posted "test2". It has different approach similar to your examples on the library home page, but in this case I'm getting this error:

![Screen Shot 2020-07-30 at 7 07 00 PM](https://user-images.githubusercontent.com/5204745/88992395-296b9600-d298-11ea-8174-9ceb4b9f6e3b.png)

This might be something easier to fix.

I'm using "react-native": "0.62.2",

**Comment by jeremycod** [comment]
I'm not sure what did you mean by: 
**But I fixed that (in master, not released on npm).** Master branch in my example, or popup-menu library?
I"m using "@breeffy/react-native-popup-menu": "^0.8.0"

BTW, to get to the screen where the problem can be reproduced, you need to navigate to "Request a refill" -> Delivery

**Comment by likern** [comment]
@jeremycod Have you set `collapsable={false}` for Views (as it was fixed in your repository)?

This must be done for every View you want to get reference to. Otherwise View can be optimized  and don't exist as real Native View.

**Comment by likern** [comment]
> I'm not sure what did you mean by:
> **But I fixed that (in master, not released on npm).** Master branch in my example, or popup-menu library?
> I"m using "@breeffy/react-native-popup-menu": "^0.8.0"
> 
> BTW, to get to the screen where the problem can be reproduced, you need to navigate to "Request a refill" -> Delivery

Sorry, my mistake. Release `0.8.0` should have these additional checks https://github.com/breeffy/react-native-popup-menu/commit/912212e83ce35423af87c98b85aeded9daf7e81f It is specifically for case when `undefined` is returned - meaning no real  native View exists (itwas optimized).

More information is here https://github.com/facebook/react-native/issues/9382

**Comment by jeremycod** [comment]
Not sure what did you mean by this last comment. I couldn't find collapsable={false} in your commit, but when I've added it, it fixed the problem. Now I have this:

```

const ElementToStick = React.forwardRef(({ style }, ref) => {
    return (
        <View
            collapsable={false}
            ref={ref}
            style={[
                {
                    padding: 0,
                    justifyContent: 'center',
                    alignItems: 'center'
                },
                style
            ]}
        />
    );
});```

**Comment by jeremycod** [comment]
Everything seems to work fine with this fix. I need to test it more thoroughly, but I guess that was the problem. Maybe that additional check you mentioned didn't work or you didn't release it in 0.8.0.

**Comment by likern** [comment]
> Not sure what did you mean by this last comment. I couldn't find collapsable={false} in your commit, but when I've added it, it fixed the problem. Now I have this:
> 
> ```
> 
> const ElementToStick = React.forwardRef(({ style }, ref) => {
>     return (
>         <View
>             collapsable={false}
>             ref={ref}
>             style={[
>                 {
>                     padding: 0,
>                     justifyContent: 'center',
>                     alignItems: 'center'
>                 },
>                 style
>             ]}
>         />
>     );
> });```
> ```

`collapsable={false}` was commit / fix in your repository.

**Comment by likern** [comment]
@jeremycod  Couldn't find `collapsable={false}` in your repository either. Probably I came across to this while investigating issue #1 and added exceptions you saw to not swallow errors.

If reference is passed to layout View React Native can optimize it out making measuring it (for positioning popup menu) impossible - hence that exception.
